import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import logo from "../assets/logo.png";
import { useContext } from "react";
import NotificationContext from "../context/NotificationContext";

const exportPDF = ({
  transactions,
  totalIncome,
  totalExpense,
  totalBalance,
  dateRange,
}) => {
  const { addNotification } = useContext(NotificationContext);
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const formatCurrency = (amount) =>
    `Rs. ${Number(amount).toLocaleString("en-IN")}`;

  // ==========================
  // Header
  // ==========================

  doc.setFillColor(99, 102, 241);
  doc.rect(0, 0, pageWidth, 30, "F");

  doc.addImage(logo, "PNG", 14, 6, 12, 12);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(255);
  doc.text("Expense Report", 30, 15);

  doc.setFontSize(10);
  doc.setTextColor(230);
  doc.text("Financial Summary & Transactions", 30, 22);

  // ==========================
  // Report Info
  // ==========================

  doc.setTextColor(0);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  doc.text(
    `Date Range : ${dateRange.startDate.toLocaleDateString(
      "en-IN"
    )} - ${dateRange.endDate
      ? dateRange.endDate.toLocaleDateString("en-IN")
      : "Present"
    }`,
    14,
    40
  );

  doc.text(
    `Generated : ${new Date().toLocaleString("en-IN")}`,
    14,
    47
  );

  doc.text(
    `Report ID : EXP-${Date.now()}`,
    14,
    54
  );

  // ==========================
  // Summary
  // ==========================

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Summary", 14, 66);

  const cardY = 72;
  const cardW = 42;
  const cardH = 24;
  const gap = 6;

  const cards = [
    {
      title: "Income",
      value: formatCurrency(totalIncome),
      bg: [220, 252, 231],
      color: [22, 163, 74],
    },
    {
      title: "Expense",
      value: formatCurrency(totalExpense),
      bg: [254, 226, 226],
      color: [239, 68, 68],
    },
    {
      title: "Balance",
      value: formatCurrency(totalBalance),
      bg: totalBalance >= 0 ? [219, 234, 254] : [254, 226, 226],
      color: totalBalance >= 0 ? [37, 99, 235] : [220, 38, 38],
    },
    {
      title: "Transactions",
      value: transactions.length.toString(),
      bg: [243, 232, 255],
      color: [126, 34, 206],
    },
  ];

  cards.forEach((card, index) => {
    const x = 14 + index * (cardW + gap);

    doc.setFillColor(...card.bg);
    doc.roundedRect(x, cardY, cardW, cardH, 3, 3, "F");

    doc.setTextColor(...card.color);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(card.title, x + 4, cardY + 8);

    doc.setTextColor(0);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.text(card.value, x + 4, cardY + 18);
  });

  // ==========================
  // Divider
  // ==========================

  doc.setDrawColor(220);
  doc.line(14, 102, 196, 102);

  doc.setTextColor(99, 102, 241);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("Transaction History", 14, 110);

  // ==========================
  // Table
  // ==========================

  autoTable(doc, {
    startY: 116,

    head: [["Transaction", "Category", "Type", "Amount (Rs)", "Date"]],

    body: transactions.map((item) => [
      item.title,
      item.category,
      item.type,
      formatCurrency(item.amount),
      new Date(item.date).toLocaleDateString("en-IN"),
    ]),

    theme: "striped",

    headStyles: {
      fillColor: [99, 102, 241],
      textColor: 255,
      fontStyle: "bold",
      halign: "center",
    },

    styles: {
      fontSize: 10,
      cellPadding: 3,
    },

    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },

    columnStyles: {
      3: {
        halign: "right",
      },
    },

    didParseCell(data) {
      if (
        data.section === "body" &&
        (data.column.index === 2 || data.column.index === 3)
      ) {
        const type = transactions[data.row.index].type;

        data.cell.styles.textColor =
          type === "income"
            ? [22, 163, 74]
            : [239, 68, 68];
      }
    },
  });

  // ==========================
  // Footer (All Pages)
  // ==========================

  const pageCount = doc.getNumberOfPages();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);

    doc.setDrawColor(220);
    doc.line(14, pageHeight - 14, pageWidth - 14, pageHeight - 14);

    doc.setFontSize(9);
    doc.setTextColor(120);

    doc.text(
      "Generated by Expense Tracker",
      14,
      pageHeight - 8
    );

    doc.text(
      new Date().toLocaleString("en-IN"),
      pageWidth / 2,
      pageHeight - 8,
      { align: "center" }
    );

    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - 14,
      pageHeight - 8,
      { align: "right" }
    );
  }

  doc.save("Expense_Report.pdf");

  addNotification({
    title: "PDF Report Exported",
    message: "Expense report exported successfully.",
    type: "report",
  });
};

export default exportPDF;